-- Create the schema to hold the tables related to this application
CREATE SCHEMA `guestbook-app`;

use `guestbook-app`;

-- To create the main table that will hold all the entries
CREATE TABLE `GUEST_BOOK_ENTRY`(
  `GUEST_BOOK_ENTRY_ID` INT NOT NULL AUTO_INCREMENT,
  `GUEST_BOOK_ENTRY_TEXT` VARCHAR(4000) NULL,
  `GUEST_BOOK_ENTRY_IMAGE` MEDIUMBLOB NULL,
  `GUEST_BOOK_ENTRY_STATUS` INT NULL,
  `GUEST_BOOK_ENTRY_CAPTURED_BY` INT NULL,
  `CREATED_BY`VARCHAR(20) NOT NULL DEFAULT 'system',
  `CREATED_ON` DATETIME NOT NULL DEFAULT NOW(),
  `MODIFIED_BY`VARCHAR(20) NOT NULL DEFAULT 'system',
  `MODIFIED_ON` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`GUEST_BOOK_ENTRY_ID`)
);

-- To create the user table that will hold all the user information
-- ROLE = ADMIN => Admin user
-- ROLE = USER => Guest user

CREATE TABLE `user`(
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_EMAIL` VARCHAR(40) NULL,
  `USER_PASSWORD` VARCHAR(2000) NULL,
  `USER_NAME` VARCHAR(45) NULL,
  `NAME` VARCHAR(45) NULL,
  `ROLE` VARCHAR(10) NOT NULL DEFAULT 'USER',
  PRIMARY KEY (`USER_ID`)
);
