spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/guestbook-app?useSSL=false"
    username: "root"
    password: "12345678"
  servlet:
    multipart:
      enabled: "false"

  # App config
server:
  port: "8080"
  application:
    name: "APi for Guest Book application"